[package]
name = "revshell"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
portable-pty = "0.8"
native-tls = "0.2"
tokio-native-tls = "0.3"
sha2 = "0.10"
base64 = "0.10"